### ISSUE TITLE
Application Installation

### ISSUE THREAD

**Issue by florian-ried** [Ruthhl3ss/public#1]
Thank you for this code!
Awesome 👍 

Any idea how to install teams via ps script in the build provisioner part? https://github.com/danielsollondon/azvmimagebuilder/blob/master/solutions/14_Building_Images_WVD/2_installTeams.ps1

**Comment by Ruthhl3ss** [comment]
Hi Florian,

I guess you are using the Packer template in HCL? 

If so, you could the following example (This is how I install Office in my environment):

build {
  sources = ["source.azure-arm.windowsvm"]
  provisioner "powershell" {
    inline = [
      "Write-host 'Mounting Azure Files as File Share'",
      "$User = '${var.azure_files_user}'",
      "$Pass = '${var.azure_files_pass}'",
      "Import-Module -Name Smbshare -Force -Scope Local",
      "New-SmbMapping -LocalPath J: -RemotePath \\\\SHARENAME\\packages -Username \"$User\" -Password \"$Pass\"",
      "if( Test-Path J:\\Office365AppsForBusiness ){ Write-Host \"'J:' drive mapped\"} else { \"Write-Host Drive not mapped\" }"
    ]
  }
    provisioner "powershell" {
    inline = [
      "Write-host 'Installing Office 365 Apps For Business'",
      "J:\\Office365AppsForBusiness\\setup.exe /configure J:\\Office365AppsForBusiness\\NKOConfig.xml",
    ]
  }
}

If this raises more questions than answering them, please let me know! :-)

**Comment by florian-ried** [comment]
Thank you so much for this fast answer :-)
Yes, I use the Packer template in HCL

In your script, I would have to define the two variables (var.azure_files_user, var_azure_files_pass) and fill them with values, right? I will try it 👍 

I could then use this solution for the installation of all applications. Many thanks! ;-)

**Comment by Ruthhl3ss** [comment]
Hi Florian,

That is correct. You need to define the two variables in order to use them in the provisioned.

I use this to install all my applications in the image. :-)

Kind Regards,

Niels

**Comment by florian-ried** [comment]
Do you use Storage Account Key as authentication? :)

**Comment by Ruthhl3ss** [comment]
In this example I do but it is better to use a Service Principal for authentication. I do put the credentials in Keyvault!

**Comment by florian-ried** [comment]
Is it possible to get the code using a service principal for authentication in the .pkr.hcl?

**Comment by Ruthhl3ss** [comment]
Please read this thread:

https://coderedirect.com/questions/657253/using-service-principal-to-access-azure-blob-storage
