### ISSUE TITLE
ARM fix for /Winget/AdobeReader/

### ISSUE THREAD

**Issue by eichmeyer** [Ruthhl3ss/public#3]
With a small fix, your code can also run on Windows on ARM:

Change:
$ResolveWingetPath = Resolve-Path "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_*_x64__8wekyb3d8bbwe"

to:
$ResolveWingetPath = Resolve-Path "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_*_*__8wekyb3d8bbwe"

I have not looked at the code for installing Winget. Here it needs surely adaptations for ARM.

**Comment by Ruthhl3ss** [comment]
Cool! Let me test that and add it. Thanks mate.
