### ISSUE TITLE
Uninstall for Winget/AdobeReader/Uninstall.ps1

### ISSUE THREAD

**Issue by henrikmai** [Ruthhl3ss/public#4]
You can not call winget (Line 12) while the path to winget is not resolved.
especially for system context uninstalls!

Changed it that way:
#Fill this variable with the Winget package ID

$PackageName = "mRemoteNG.mRemoteNG"

#Creating Loggin Folder
if (!(Test-Path -Path C:\ProgramData\WinGetLogs)) {
    New-Item -Path C:\ProgramData\WinGetLogs -Force -ItemType Directory
}
#Start Logging
Start-Transcript -Path "C:\ProgramData\Microsoft\IntuneManagementExtension\Logs\$($PackageName)_Uninstall.log" -Append

#Get Winget path
try {        
    $ResolveWingetPath = Resolve-Path "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_*_x64__8wekyb3d8bbwe"
    if ($ResolveWingetPath){
           $WingetPath = $ResolveWingetPath[-1].Path
    }    
 
}
catch {
    Throw "Failed to Winget Install Path"
}

#Detect Apps
$InstalledApps = & $WingetPath\winget.exe list --id $PackageName

if ($InstalledApps) {
    
    Write-Host "Trying to uninstall $($PackageName)"
    
    #try {        
    #    $ResolveWingetPath = Resolve-Path "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_*_x64__8wekyb3d8bbwe"
    #    if ($ResolveWingetPath){
    #           $WingetPath = $ResolveWingetPath[-1].Path
    #    }
    
        $config
        
        & $WingetPath\winget.exe uninstall $PackageName --silent
    }
    #catch {
    #    Throw "Failed to uninstall $($PackageName)"
    #}
#}
else {
    Write-Host "$($PackageName) is not installed or detected"
}

Stop-Transcript

**Comment by Ruthhl3ss** [comment]
Thanks, I will fix this.
